name = "NMRQuantumSim"
uuid = "99884b55-e3bc-4dff-bd73-764a97c6da8e"
authors = ["Van Vincent Duong <vince.duong97@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
